# MySQL Data Source
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/carestream_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:ADST@143}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
carestream.app.jwtSecret=${JWT_SECRET:carestreamSecretKey2024XYZabcdefghijklmnopqrstuvwxyz0123456789}
carestream.app.jwtExpirationMs=86400000

# Error Handling
server.error.include-message=always
