# MySQL Data Source
spring.datasource.url=${DB_URL:jdbc:mysql://autorack.proxy.rlwy.net:22508/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:wIoOaterkgkhOSGLisipBMgqfkftgUio}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
carestream.app.jwtSecret=${JWT_SECRET:CareStreamSecretKeyThatIsLongEnoughToBeSecureForHS256AlgorithmUsingSpringSecurity6AndJJWT11}
carestream.app.jwtExpirationMs=86400000

# Error Handling
server.error.include-message=always
