# MySQL Data Source
spring.datasource.url=jdbc:mysql://localhost:3306/carestream_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ADST@143
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
carestream.app.jwtSecret=CareStreamSecretKeyThatIsLongEnoughToBeSecureForHS256AlgorithmUsingSpringSecurity6AndJJWT11
carestream.app.jwtExpirationMs=86400000

# Error Handling
server.error.include-message=always
